# : Manager [[[

[mgr]
cwd = { fg = "#ffffff" }

# Tab
tab_active = { fg = "#e6e1e5", bg = "#b8bb26", bold = true }
tab_inactive = { fg = "#6a6c0f", bg = "#ffffff" }
tab_width = 1

# Find
find_keyword = { fg = "#fb4934", bold = true, italic = true, underline = true }
find_position = { fg = "#fb4934", bold = true, italic = true }

# Marker
marker_copied = { fg = "#396051", bg = "#396051" }
marker_cut = { fg = "#396051", bg = "#396051" }
marker_marked = { fg = "#fb4934", bg = "#fb4934" }
marker_selected = { fg = "#83a598", bg = "#83a598" }

# Count
count_copied = { fg = "#ffffff", bg = "#396051" }
count_cut = { fg = "#ffffff", bg = "#396051" }
count_selected = { fg = "#e6e1e5", bg = "#83a598" }

# Border
border_style  = { fg = "#b8bb26" }

# : ]]]


# : Status [[[

[status]
separator_style = { bg = "#e6e1e5", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#b8bb26", fg = "#e6e1e5", bold = true }
normal_alt  = { bg = "#353535", fg = "#ffffff" }

# Select mode
select_main = { bg = "#fabd2f", fg = "#000000", bold = true }
select_alt  = { bg = "#353535", fg = "#ffffff" }

# Unset mode
unset_main = { bg = "#83a598", fg = "#e6e1e5", bold = true }
unset_alt  = { bg = "#353535", fg = "#ffffff" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#b8bb26", bg = "#282828" }
progress_error = { fg = "#fb4934", bg = "#282828" }

# Permissions
permissions_t = { fg = "#fabd2f" }
permissions_w = { fg = "#83a598" }
permissions_x = { fg = "#fb4934" }
permissions_r = { fg = "#396051" }
permissions_s = { fg = "#6a6c0f" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#b8bb26" }
active = { fg = "#83a598", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#b8bb26" }
value = { fg = "#ffffff" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#b8bb26", bold = true, bg = "#282828" }
inactive = { fg = "#fabd2f", bg = "#282828" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#b8bb26", bg = "#e6e1e5" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#b8bb26" }
title = {}
hovered = { fg = "#396051", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#282828" }
cand = { fg = "#b8bb26" }
rest = { fg = "#e6e1e5" }
desc = { fg = "#ffffff" }
separator = " â–¶ "
separator_style = { fg = "#ffffff" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#ffffff" }
run = { fg = "#ffffff" }
footer = { fg = "#000000", bg = "#fabd2f" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#83a598" }
title_warn = { fg = "#b8bb26" }
title_error = { fg = "#fb4934" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#991000" },
    { name = "*", is = "exec", fg = "#ffffff" },

    # Fallback
    { name = "*", fg = "#ffffff" },
    { name = "*/", fg = "#b8bb26" },
]

# : ]]]
