[general]
import = [
   "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
#decorations = "None"
opacity = 0.8

[window.padding]
x = 10
y = 10

[font]
size = 9.5

# [font.normal]
# family = "JetBrainsMono"
# style = "Regular"

[cursor.style]
shape = "Block"
blinking = "Always"

[selection]
save_to_clipboard = true

#[terminal.shell]
#program = "/usr/bin/fish"
# TODO add image preview usng uzb++ 
