[general]
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
   "~/.config/alacritty/catppuccin-mocha.toml"
  # "~/.config/alacritty/tokyo-night.toml"
  # "~/.config/alacritty/tokyo-night-storm.toml"
  # "~/.config/alacritty/tokyonight_day.toml"
  # "~/.config/alacritty/tokyonight_moon.toml"
  # "~/.config/alacritty/tokyonight_night.toml"
  # "~/.config/alacritty/tokyonight_storm.toml"
]

[window]
decorations = "None"
opacity = 1

[window.padding]
x = 10
y = 10

[font]
size = 8.0

# [font.normal]
# family = "JetBrainsMono"
# style = "Regular"

[cursor.style]
shape = "Block"
blinking = "Always"

[selection]
save_to_clipboard = true

#[terminal.shell]
#program = "/usr/bin/fish"
